# Check `mdhpnet/utils/simple_logger.py` for more details.

BASIC:
  level: INFO
  to_console: true
  save_path: "logs/basic.log"
  mode: "a"
  max_bytes: 1048576
  backup_count: 10 
  log_fmt: "[%(asctime)s][%(levelname)s][%(module)s:L%(lineno)d] >>> %(message)s"

TRAIN:
  level: INFO
  to_console: false
  save_path: "logs/train.log"
  mode: "a"
  max_bytes: 1048576
  backup_count: 10 
  log_fmt: "[%(asctime)s][%(levelname)s][%(module)s:L%(lineno)d] >>> %(message)s"

TEST:
  level: INFO
  to_console: false
  save_path: "logs/test.log"
  mode: "a"
  max_bytes: 1048576
  backup_count: 10 
  log_fmt: "[%(asctime)s][%(levelname)s][%(module)s:L%(lineno)d] >>> %(message)s"

MDHP_GDS:
  level: INFO  # If set to "DEBUG", loss of each epoch would be logged.
  to_console: false
  save_path: "logs/mdhp_gds.log"
  mode: "a"
  max_bytes: 1048576
  backup_count: 10 
  log_fmt: "[%(asctime)s][%(levelname)s][%(module)s:L%(lineno)d] >>> %(message)s"